## This file was automatically generated by odin.
## Do not edit by hand as changes will be lost.
.R6_model_mock_yield <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "model_mock_yield",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("model_mock_yield_create", user, use_dde, PACKAGE = "cellularfluparams")
      self$use_dde <- use_dde
      self$init <- .Call("model_mock_yield_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_model_mock_yield_set_user", self$ptr, user, PACKAGE = "cellularfluparams")
      self$init <- .Call("model_mock_yield_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("model_mock_yield_variable_order", self$ptr, PACKAGE = "cellularfluparams")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("model_mock_yield_deriv_r", self$ptr, t, y, PACKAGE = "cellularfluparams")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "model_mock_yield_deriv_dde", self$ptr,
                          dllname = "cellularfluparams",
                          parms_are_real = FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::ode(y, t, "model_mock_yield_deriv_ds", self$ptr,
                            initfunc = "model_mock_yield_initmod_ds", dllname = "cellularfluparams",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("model_mock_yield_contents", self$ptr, PACKAGE = "cellularfluparams")
    },

    user_info = function() {
      data.frame(
        name = c("V_0", "c"),
        has_default = c(FALSE, FALSE),
        default_value = I(list(NULL, NULL)),
        rank = c(0, 0),
        stringsAsFactors = FALSE)
    },

    graph_data = function() {
      structure(
        list(
          discrete = FALSE,
          stochastic = FALSE,
          nodes = data.frame(
            id = c("V", "V_0", "c", "initial_V", "deriv_V"),
            label = c("V", "V_0", "c", "initial(V)", "deriv(V)"),
            name_target = c("V", "V_0", "c", "V", "V"),
            rank = c(0, 0, 0, 0, 0),
            type = c("variable", "user", "user", "initial", "target"),
            stage = c("time", "user", "user", "user", "time"),
            stringsAsFactors = FALSE),
          edges = data.frame(
            from = c("V_0", "c", "V"),
            to = c("initial_V", "deriv_V", "deriv_V"),
            stringsAsFactors = FALSE)),
        class = "odin_graph_data")
    }
  ))
model_mock_yield <- function(V_0, c, user = list(V_0 = V_0, c = c), use_dde = FALSE) {
  .R6_model_mock_yield$new(user = user, use_dde = use_dde)
}
attr(model_mock_yield, "user_info") <- .R6_model_mock_yield$public_methods$user_info
attr(model_mock_yield, "graph_data") <- .R6_model_mock_yield$public_methods$graph_data
class(model_mock_yield) <- "odin_generator"
model_mock_yield
.R6_model_teiv_stages_dual_linear_p <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "model_teiv_stages_dual_linear_p",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("model_teiv_stages_dual_linear_p_create", user, use_dde, PACKAGE = "cellularfluparams")
      self$use_dde <- use_dde
      self$init <- .Call("model_teiv_stages_dual_linear_p_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_model_teiv_stages_dual_linear_p_set_user", self$ptr, user, PACKAGE = "cellularfluparams")
      self$init <- .Call("model_teiv_stages_dual_linear_p_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      self$update_cache()
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("model_teiv_stages_dual_linear_p_variable_order", self$ptr, PACKAGE = "cellularfluparams")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("model_teiv_stages_dual_linear_p_deriv_r", self$ptr, t, y, PACKAGE = "cellularfluparams")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "model_teiv_stages_dual_linear_p_deriv_dde", self$ptr,
                          dllname = "cellularfluparams",
                          parms_are_real = FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::ode(y, t, "model_teiv_stages_dual_linear_p_deriv_ds", self$ptr,
                            initfunc = "model_teiv_stages_dual_linear_p_initmod_ds", dllname = "cellularfluparams",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("model_teiv_stages_dual_linear_p_contents", self$ptr, PACKAGE = "cellularfluparams")
    },

    user_info = function() {
      data.frame(
        name = c("n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "L_0", "I_0"),
        has_default = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        default_value = I(list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, structure(list(L_0 = NULL), .Names = "L_0"), structure(list(I_0 = NULL), .Names = "I_0"))),
        rank = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1),
        stringsAsFactors = FALSE)
    },

    graph_data = function() {
      structure(
        list(
          discrete = FALSE,
          stochastic = FALSE,
          nodes = data.frame(
            id = c("T1", "V_inf", "V_tot", "L", "I", "n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "initial_T1", "initial_V_inf", "initial_V_tot", "dim_L", "dim_I", "dim_L_0", "dim_I_0", "dim_I_scale_vec", "L_0", "initial_L", "I_0", "initial_I", "deriv_T1", "deriv_L", "deriv_I", "I_scale_vec", "deriv_V_inf", "deriv_V_tot"),
            label = c("T1", "V_inf", "V_tot", "L", "I", "n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "initial(T1)", "initial(V_inf)", "initial(V_tot)", "dim(L)", "dim(I)", "dim(L_0)", "dim(I_0)", "dim(I_scale_vec)", "L_0", "initial(L)", "I_0", "initial(I)", "deriv(T1)", "deriv(L)", "deriv(I)", "I_scale_vec", "deriv(V_inf)", "deriv(V_tot)"),
            name_target = c("T1", "V_inf", "V_tot", "L", "I", "n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "T1", "V_inf", "V_tot", "L", "I", "L_0", "I_0", "I_scale_vec", "L_0", "L", "I_0", "I", "T1", "L", "I", "I_scale_vec", "V_inf", "V_tot"),
            rank = c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0),
            type = c("variable", "variable", "variable", "variable", "variable", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "initial", "initial", "initial", "dim", "dim", "dim", "dim", "dim", "user", "initial", "user", "initial", "target", "target", "target", "other", "target", "target"),
            stage = c("time", "time", "time", "time", "time", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "time", "time", "time", "time", "time", "time"),
            stringsAsFactors = FALSE),
          edges = data.frame(
            from = c("T_0", "V_inf_0", "V_tot_0", "n_L", "n_I", "n_L", "n_I", "n_I", "dim_L_0", "n_L", "dim_L", "L_0", "i", "dim_I_0", "n_I", "dim_I", "I_0", "i", "beta", "T1", "V_inf", "dim_L", "beta", "T1", "V_inf", "k1", "n_L", "L", "i", "dim_I", "k1", "n_L", "L", "delta", "n_I", "I", "i", "n_I", "dim_I_scale_vec", "i", "I", "p_inf", "I_scale_vec", "c_inf", "V_inf", "beta_inf", "T1", "p_tot", "I_scale_vec", "c_tot", "V_tot", "beta_tot", "T1", "V_inf"),
            to = c("initial_T1", "initial_V_inf", "initial_V_tot", "dim_L", "dim_I", "dim_L_0", "dim_I_0", "dim_I_scale_vec", "L_0", "initial_L", "initial_L", "initial_L", "initial_L", "I_0", "initial_I", "initial_I", "initial_I", "initial_I", "deriv_T1", "deriv_T1", "deriv_T1", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "I_scale_vec", "I_scale_vec", "I_scale_vec", "I_scale_vec", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot"),
            stringsAsFactors = FALSE)),
        class = "odin_graph_data")
    }
  ))
model_teiv_stages_dual_linear_p <- function(n_L, n_I, beta, beta_inf, beta_tot, k1, delta, p_inf, p_tot, c_inf, c_tot, T_0, V_inf_0, V_tot_0, L_0, I_0, user = list(n_L = n_L, n_I = n_I, beta = beta, beta_inf = beta_inf, beta_tot = beta_tot, k1 = k1, delta = delta, p_inf = p_inf, p_tot = p_tot, c_inf = c_inf, c_tot = c_tot, T_0 = T_0, V_inf_0 = V_inf_0, V_tot_0 = V_tot_0, L_0 = L_0, I_0 = I_0), use_dde = FALSE) {
  .R6_model_teiv_stages_dual_linear_p$new(user = user, use_dde = use_dde)
}
attr(model_teiv_stages_dual_linear_p, "user_info") <- .R6_model_teiv_stages_dual_linear_p$public_methods$user_info
attr(model_teiv_stages_dual_linear_p, "graph_data") <- .R6_model_teiv_stages_dual_linear_p$public_methods$graph_data
class(model_teiv_stages_dual_linear_p) <- "odin_generator"
model_teiv_stages_dual_linear_p
.R6_model_teiv_stages_dual <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "model_teiv_stages_dual",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("model_teiv_stages_dual_create", user, use_dde, PACKAGE = "cellularfluparams")
      self$use_dde <- use_dde
      self$init <- .Call("model_teiv_stages_dual_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_model_teiv_stages_dual_set_user", self$ptr, user, PACKAGE = "cellularfluparams")
      self$init <- .Call("model_teiv_stages_dual_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      self$update_cache()
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("model_teiv_stages_dual_variable_order", self$ptr, PACKAGE = "cellularfluparams")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("model_teiv_stages_dual_deriv_r", self$ptr, t, y, PACKAGE = "cellularfluparams")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "model_teiv_stages_dual_deriv_dde", self$ptr,
                          dllname = "cellularfluparams",
                          parms_are_real = FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::ode(y, t, "model_teiv_stages_dual_deriv_ds", self$ptr,
                            initfunc = "model_teiv_stages_dual_initmod_ds", dllname = "cellularfluparams",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("model_teiv_stages_dual_contents", self$ptr, PACKAGE = "cellularfluparams")
    },

    user_info = function() {
      data.frame(
        name = c("n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "L_0", "I_0"),
        has_default = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        default_value = I(list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, structure(list(L_0 = NULL), .Names = "L_0"), structure(list(I_0 = NULL), .Names = "I_0"))),
        rank = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1),
        stringsAsFactors = FALSE)
    },

    graph_data = function() {
      structure(
        list(
          discrete = FALSE,
          stochastic = FALSE,
          nodes = data.frame(
            id = c("T1", "V_inf", "V_tot", "L", "I", "n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "initial_T1", "initial_V_inf", "initial_V_tot", "dim_L", "dim_I", "dim_L_0", "dim_I_0", "L_0", "initial_L", "I_0", "initial_I", "deriv_T1", "deriv_V_inf", "deriv_V_tot", "deriv_L", "deriv_I"),
            label = c("T1", "V_inf", "V_tot", "L", "I", "n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "initial(T1)", "initial(V_inf)", "initial(V_tot)", "dim(L)", "dim(I)", "dim(L_0)", "dim(I_0)", "L_0", "initial(L)", "I_0", "initial(I)", "deriv(T1)", "deriv(V_inf)", "deriv(V_tot)", "deriv(L)", "deriv(I)"),
            name_target = c("T1", "V_inf", "V_tot", "L", "I", "n_L", "n_I", "beta", "beta_inf", "beta_tot", "k1", "delta", "p_inf", "p_tot", "c_inf", "c_tot", "T_0", "V_inf_0", "V_tot_0", "T1", "V_inf", "V_tot", "L", "I", "L_0", "I_0", "L_0", "L", "I_0", "I", "T1", "V_inf", "V_tot", "L", "I"),
            rank = c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1),
            type = c("variable", "variable", "variable", "variable", "variable", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "initial", "initial", "initial", "dim", "dim", "dim", "dim", "user", "initial", "user", "initial", "target", "target", "target", "target", "target"),
            stage = c("time", "time", "time", "time", "time", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "time", "time", "time", "time", "time"),
            stringsAsFactors = FALSE),
          edges = data.frame(
            from = c("T_0", "V_inf_0", "V_tot_0", "n_L", "n_I", "n_L", "n_I", "dim_L_0", "n_L", "dim_L", "L_0", "i", "dim_I_0", "n_I", "dim_I", "I_0", "i", "beta", "T1", "V_inf", "p_inf", "I", "c_inf", "V_inf", "beta_inf", "T1", "p_tot", "I", "c_tot", "V_tot", "beta_tot", "T1", "V_inf", "dim_L", "beta", "T1", "V_inf", "k1", "n_L", "L", "i", "dim_I", "k1", "n_L", "L", "delta", "n_I", "I", "i"),
            to = c("initial_T1", "initial_V_inf", "initial_V_tot", "dim_L", "dim_I", "dim_L_0", "dim_I_0", "L_0", "initial_L", "initial_L", "initial_L", "initial_L", "I_0", "initial_I", "initial_I", "initial_I", "initial_I", "deriv_T1", "deriv_T1", "deriv_T1", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_inf", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_V_tot", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I"),
            stringsAsFactors = FALSE)),
        class = "odin_graph_data")
    }
  ))
model_teiv_stages_dual <- function(n_L, n_I, beta, beta_inf, beta_tot, k1, delta, p_inf, p_tot, c_inf, c_tot, T_0, V_inf_0, V_tot_0, L_0, I_0, user = list(n_L = n_L, n_I = n_I, beta = beta, beta_inf = beta_inf, beta_tot = beta_tot, k1 = k1, delta = delta, p_inf = p_inf, p_tot = p_tot, c_inf = c_inf, c_tot = c_tot, T_0 = T_0, V_inf_0 = V_inf_0, V_tot_0 = V_tot_0, L_0 = L_0, I_0 = I_0), use_dde = FALSE) {
  .R6_model_teiv_stages_dual$new(user = user, use_dde = use_dde)
}
attr(model_teiv_stages_dual, "user_info") <- .R6_model_teiv_stages_dual$public_methods$user_info
attr(model_teiv_stages_dual, "graph_data") <- .R6_model_teiv_stages_dual$public_methods$graph_data
class(model_teiv_stages_dual) <- "odin_generator"
model_teiv_stages_dual
.R6_model_teiv_stages_gen_G_inoculum <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "model_teiv_stages_gen_G_inoculum",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("model_teiv_stages_gen_G_inoculum_create", user, use_dde, PACKAGE = "cellularfluparams")
      self$use_dde <- use_dde
      self$init <- .Call("model_teiv_stages_gen_G_inoculum_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_model_teiv_stages_gen_G_inoculum_set_user", self$ptr, user, PACKAGE = "cellularfluparams")
      self$init <- .Call("model_teiv_stages_gen_G_inoculum_initialise", self$ptr, NA_real_, PACKAGE = "cellularfluparams")
      self$update_cache()
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("model_teiv_stages_gen_G_inoculum_variable_order", self$ptr, PACKAGE = "cellularfluparams")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("model_teiv_stages_gen_G_inoculum_deriv_r", self$ptr, t, y, PACKAGE = "cellularfluparams")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "model_teiv_stages_gen_G_inoculum_deriv_dde", self$ptr,
                          dllname = "cellularfluparams",
                          parms_are_real = FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::ode(y, t, "model_teiv_stages_gen_G_inoculum_deriv_ds", self$ptr,
                            initfunc = "model_teiv_stages_gen_G_inoculum_initmod_ds", dllname = "cellularfluparams",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("model_teiv_stages_gen_G_inoculum_contents", self$ptr, PACKAGE = "cellularfluparams")
    },

    user_info = function() {
      data.frame(
        name = c("n_L", "n_I", "beta", "beta_inf", "delta", "p_inf", "c_inf", "T_0", "V_inf_0", "G", "k1", "L_0", "I_0"),
        has_default = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        default_value = I(list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, structure(list(L_0 = NULL), .Names = "L_0"), structure(list(I_0 = NULL), .Names = "I_0"))),
        rank = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2),
        stringsAsFactors = FALSE)
    },

    graph_data = function() {
      structure(
        list(
          discrete = FALSE,
          stochastic = FALSE,
          nodes = data.frame(
            id = c("T1", "L", "I", "V", "W", "n_L", "n_I", "beta", "beta_inf", "delta", "p_inf", "c_inf", "T_0", "V_inf_0", "G", "k1", "dim_L", "dim_I", "dim_V", "dim_W", "dim_L_0", "dim_I_0", "initial_T1", "initial_V", "initial_W", "L_0", "initial_L", "I_0", "initial_I", "deriv_T1", "deriv_L", "deriv_I", "deriv_V", "deriv_W"),
            label = c("T1", "L", "I", "V", "W", "n_L", "n_I", "beta", "beta_inf", "delta", "p_inf", "c_inf", "T_0", "V_inf_0", "G", "k1", "dim(L)", "dim(I)", "dim(V)", "dim(W)", "dim(L_0)", "dim(I_0)", "initial(T1)", "initial(V)", "initial(W)", "L_0", "initial(L)", "I_0", "initial(I)", "deriv(T1)", "deriv(L)", "deriv(I)", "deriv(V)", "deriv(W)"),
            name_target = c("T1", "L", "I", "V", "W", "n_L", "n_I", "beta", "beta_inf", "delta", "p_inf", "c_inf", "T_0", "V_inf_0", "G", "k1", "L", "I", "V", "W", "L_0", "I_0", "T1", "V", "W", "L_0", "L", "I_0", "I", "T1", "L", "I", "V", "W"),
            rank = c(0, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 0, 2, 2, 1, 1),
            type = c("variable", "variable", "variable", "variable", "variable", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "dim", "dim", "dim", "dim", "dim", "dim", "initial", "initial", "initial", "user", "initial", "user", "initial", "target", "target", "target", "target", "target"),
            stage = c("time", "time", "time", "time", "time", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "user", "time", "time", "time", "time", "time"),
            stringsAsFactors = FALSE),
          edges = data.frame(
            from = c("n_L", "G", "n_I", "G", "G", "G", "n_L", "G", "n_I", "G", "T_0", "dim_V", "V_inf_0", "G", "dim_W", "V_inf_0", "G", "dim_L_0", "n_L", "G", "dim_L", "L_0", "i", "j", "dim_I_0", "n_I", "G", "dim_I", "I_0", "i", "j", "beta", "T1", "V", "G", "dim_L", "beta", "T1", "V", "j", "k1", "n_L", "L", "i", "G", "dim_I", "k1", "n_L", "L", "j", "delta", "n_I", "I", "i", "dim_V", "c_inf", "beta_inf", "T1", "V", "G", "p_inf", "I", "dim_I", "i", "dim_W", "G", "p_inf", "I", "dim_I", "i"),
            to = c("dim_L", "dim_L", "dim_I", "dim_I", "dim_V", "dim_W", "dim_L_0", "dim_L_0", "dim_I_0", "dim_I_0", "initial_T1", "initial_V", "initial_V", "initial_V", "initial_W", "initial_W", "initial_W", "L_0", "initial_L", "initial_L", "initial_L", "initial_L", "initial_L", "initial_L", "I_0", "initial_I", "initial_I", "initial_I", "initial_I", "initial_I", "initial_I", "deriv_T1", "deriv_T1", "deriv_T1", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_L", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_I", "deriv_V", "deriv_V", "deriv_V", "deriv_V", "deriv_V", "deriv_V", "deriv_V", "deriv_V", "deriv_V", "deriv_V", "deriv_W", "deriv_W", "deriv_W", "deriv_W", "deriv_W", "deriv_W"),
            stringsAsFactors = FALSE)),
        class = "odin_graph_data")
    }
  ))
model_teiv_stages_gen_G_inoculum <- function(n_L, n_I, beta, beta_inf, delta, p_inf, c_inf, T_0, V_inf_0, G, k1, L_0, I_0, user = list(n_L = n_L, n_I = n_I, beta = beta, beta_inf = beta_inf, delta = delta, p_inf = p_inf, c_inf = c_inf, T_0 = T_0, V_inf_0 = V_inf_0, G = G, k1 = k1, L_0 = L_0, I_0 = I_0), use_dde = FALSE) {
  .R6_model_teiv_stages_gen_G_inoculum$new(user = user, use_dde = use_dde)
}
attr(model_teiv_stages_gen_G_inoculum, "user_info") <- .R6_model_teiv_stages_gen_G_inoculum$public_methods$user_info
attr(model_teiv_stages_gen_G_inoculum, "graph_data") <- .R6_model_teiv_stages_gen_G_inoculum$public_methods$graph_data
class(model_teiv_stages_gen_G_inoculum) <- "odin_generator"
model_teiv_stages_gen_G_inoculum
